theme = "vvs"
languageCode = "en-us"
title = "Brian Liston | Digital Design and Video Production in Denver, Colorado"
baseURL = "http://www.brianliston.com/"
publishDir = "docs"
paginate = 8
pluralizeListTitles = false
googleAnalytics = "UA-91465340-1"

[taxonomies]
tag = "tags"
category = "categories"
homepage = "homepage"