theme = "poco"
languageCode = "en-us"
title = "Poco A Poco | Digital Design and Video Production in Denver, Colorado"
baseURL = "http://pocoapocostudio.com/"
publishDir = "docs"
paginate = 8
pluralizeListTitles = false
googleAnalytics = "UA-91465340-1"

[taxonomies]
tag = "tags"
category = "categories"
homepage = "homepage"