name = "VVS"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = ""
homepage = "http://brianliston.com/"
tags = []
features = []
min_version = 0.19

[author]
  name = "Brian Liston"
  homepage = "http://brianliston.com/"
